# CMake generated Testfile for 
# Source directory: C:/Users/YW/Documents/GitHub/CMacIonize/test
# Build directory: C:/Users/YW/Documents/GitHub/CMacIonize/0/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testLineCoolingData "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testLineCoolingData.exe")
  set_tests_properties(testLineCoolingData PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testLineCoolingData "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testLineCoolingData.exe")
  set_tests_properties(testLineCoolingData PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testLineCoolingData "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testLineCoolingData.exe")
  set_tests_properties(testLineCoolingData PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testLineCoolingData "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testLineCoolingData.exe")
  set_tests_properties(testLineCoolingData PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testLineCoolingData NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testCommandLineParser "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testCommandLineParser.exe")
  set_tests_properties(testCommandLineParser PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testCommandLineParser "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testCommandLineParser.exe")
  set_tests_properties(testCommandLineParser PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testCommandLineParser "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testCommandLineParser.exe")
  set_tests_properties(testCommandLineParser PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testCommandLineParser "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testCommandLineParser.exe")
  set_tests_properties(testCommandLineParser PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testCommandLineParser NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testCartesianDensityGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testCartesianDensityGrid.exe")
  set_tests_properties(testCartesianDensityGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testCartesianDensityGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testCartesianDensityGrid.exe")
  set_tests_properties(testCartesianDensityGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testCartesianDensityGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testCartesianDensityGrid.exe")
  set_tests_properties(testCartesianDensityGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testCartesianDensityGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testCartesianDensityGrid.exe")
  set_tests_properties(testCartesianDensityGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testCartesianDensityGrid NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testCoordinateVector "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testCoordinateVector.exe")
  set_tests_properties(testCoordinateVector PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testCoordinateVector "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testCoordinateVector.exe")
  set_tests_properties(testCoordinateVector PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testCoordinateVector "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testCoordinateVector.exe")
  set_tests_properties(testCoordinateVector PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testCoordinateVector "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testCoordinateVector.exe")
  set_tests_properties(testCoordinateVector PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testCoordinateVector NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testPhotonSource.exe")
  set_tests_properties(testPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testPhotonSource.exe")
  set_tests_properties(testPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testPhotonSource.exe")
  set_tests_properties(testPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testPhotonSource.exe")
  set_tests_properties(testPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testPhotonSource NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testPhotonSourceSpectrum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testPhotonSourceSpectrum.exe")
  set_tests_properties(testPhotonSourceSpectrum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testPhotonSourceSpectrum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testPhotonSourceSpectrum.exe")
  set_tests_properties(testPhotonSourceSpectrum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testPhotonSourceSpectrum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testPhotonSourceSpectrum.exe")
  set_tests_properties(testPhotonSourceSpectrum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testPhotonSourceSpectrum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testPhotonSourceSpectrum.exe")
  set_tests_properties(testPhotonSourceSpectrum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testPhotonSourceSpectrum NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testVernerCrossSections "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testVernerCrossSections.exe")
  set_tests_properties(testVernerCrossSections PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testVernerCrossSections "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testVernerCrossSections.exe")
  set_tests_properties(testVernerCrossSections PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testVernerCrossSections "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testVernerCrossSections.exe")
  set_tests_properties(testVernerCrossSections PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testVernerCrossSections "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testVernerCrossSections.exe")
  set_tests_properties(testVernerCrossSections PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testVernerCrossSections NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testParameterFile "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testParameterFile.exe")
  set_tests_properties(testParameterFile PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testParameterFile "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testParameterFile.exe")
  set_tests_properties(testParameterFile PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testParameterFile "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testParameterFile.exe")
  set_tests_properties(testParameterFile PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testParameterFile "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testParameterFile.exe")
  set_tests_properties(testParameterFile PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testParameterFile NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testVernerRecombinationRates "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testVernerRecombinationRates.exe")
  set_tests_properties(testVernerRecombinationRates PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testVernerRecombinationRates "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testVernerRecombinationRates.exe")
  set_tests_properties(testVernerRecombinationRates PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testVernerRecombinationRates "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testVernerRecombinationRates.exe")
  set_tests_properties(testVernerRecombinationRates PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testVernerRecombinationRates "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testVernerRecombinationRates.exe")
  set_tests_properties(testVernerRecombinationRates PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testVernerRecombinationRates NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testRandomGenerator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testRandomGenerator.exe")
  set_tests_properties(testRandomGenerator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testRandomGenerator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testRandomGenerator.exe")
  set_tests_properties(testRandomGenerator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testRandomGenerator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testRandomGenerator.exe")
  set_tests_properties(testRandomGenerator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testRandomGenerator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testRandomGenerator.exe")
  set_tests_properties(testRandomGenerator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testRandomGenerator NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testLog "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testLog.exe")
  set_tests_properties(testLog PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testLog "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testLog.exe")
  set_tests_properties(testLog PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testLog "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testLog.exe")
  set_tests_properties(testLog PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testLog "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testLog.exe")
  set_tests_properties(testLog PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testLog NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testUnitConverter "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testUnitConverter.exe")
  set_tests_properties(testUnitConverter PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testUnitConverter "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testUnitConverter.exe")
  set_tests_properties(testUnitConverter PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testUnitConverter "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testUnitConverter.exe")
  set_tests_properties(testUnitConverter PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testUnitConverter "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testUnitConverter.exe")
  set_tests_properties(testUnitConverter PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testUnitConverter NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testAsciiFileDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testAsciiFileDensityFunction.exe")
  set_tests_properties(testAsciiFileDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testAsciiFileDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testAsciiFileDensityFunction.exe")
  set_tests_properties(testAsciiFileDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testAsciiFileDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testAsciiFileDensityFunction.exe")
  set_tests_properties(testAsciiFileDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testAsciiFileDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testAsciiFileDensityFunction.exe")
  set_tests_properties(testAsciiFileDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testAsciiFileDensityFunction NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testOctree "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testOctree.exe")
  set_tests_properties(testOctree PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testOctree "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testOctree.exe")
  set_tests_properties(testOctree PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testOctree "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testOctree.exe")
  set_tests_properties(testOctree PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testOctree "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testOctree.exe")
  set_tests_properties(testOctree PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testOctree NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testAMRGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testAMRGrid.exe")
  set_tests_properties(testAMRGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testAMRGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testAMRGrid.exe")
  set_tests_properties(testAMRGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testAMRGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testAMRGrid.exe")
  set_tests_properties(testAMRGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testAMRGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testAMRGrid.exe")
  set_tests_properties(testAMRGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testAMRGrid NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testSILCCPhotonSourceDistribution "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testSILCCPhotonSourceDistribution.exe")
  set_tests_properties(testSILCCPhotonSourceDistribution PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testSILCCPhotonSourceDistribution "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testSILCCPhotonSourceDistribution.exe")
  set_tests_properties(testSILCCPhotonSourceDistribution PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testSILCCPhotonSourceDistribution "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testSILCCPhotonSourceDistribution.exe")
  set_tests_properties(testSILCCPhotonSourceDistribution PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testSILCCPhotonSourceDistribution "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testSILCCPhotonSourceDistribution.exe")
  set_tests_properties(testSILCCPhotonSourceDistribution PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testSILCCPhotonSourceDistribution NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testIonizationStateCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testIonizationStateCalculator.exe")
  set_tests_properties(testIonizationStateCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testIonizationStateCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testIonizationStateCalculator.exe")
  set_tests_properties(testIonizationStateCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testIonizationStateCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testIonizationStateCalculator.exe")
  set_tests_properties(testIonizationStateCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testIonizationStateCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testIonizationStateCalculator.exe")
  set_tests_properties(testIonizationStateCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testIonizationStateCalculator NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testAMRDensityGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testAMRDensityGrid.exe")
  set_tests_properties(testAMRDensityGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testAMRDensityGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testAMRDensityGrid.exe")
  set_tests_properties(testAMRDensityGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testAMRDensityGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testAMRDensityGrid.exe")
  set_tests_properties(testAMRDensityGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testAMRDensityGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testAMRDensityGrid.exe")
  set_tests_properties(testAMRDensityGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testAMRDensityGrid NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testSpatialAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testSpatialAMRRefinementScheme.exe")
  set_tests_properties(testSpatialAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testSpatialAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testSpatialAMRRefinementScheme.exe")
  set_tests_properties(testSpatialAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testSpatialAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testSpatialAMRRefinementScheme.exe")
  set_tests_properties(testSpatialAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testSpatialAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testSpatialAMRRefinementScheme.exe")
  set_tests_properties(testSpatialAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testSpatialAMRRefinementScheme NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testOpacityAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testOpacityAMRRefinementScheme.exe")
  set_tests_properties(testOpacityAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testOpacityAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testOpacityAMRRefinementScheme.exe")
  set_tests_properties(testOpacityAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testOpacityAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testOpacityAMRRefinementScheme.exe")
  set_tests_properties(testOpacityAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testOpacityAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testOpacityAMRRefinementScheme.exe")
  set_tests_properties(testOpacityAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testOpacityAMRRefinementScheme NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testIsotropicContinuousPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testIsotropicContinuousPhotonSource.exe")
  set_tests_properties(testIsotropicContinuousPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testIsotropicContinuousPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testIsotropicContinuousPhotonSource.exe")
  set_tests_properties(testIsotropicContinuousPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testIsotropicContinuousPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testIsotropicContinuousPhotonSource.exe")
  set_tests_properties(testIsotropicContinuousPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testIsotropicContinuousPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testIsotropicContinuousPhotonSource.exe")
  set_tests_properties(testIsotropicContinuousPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testIsotropicContinuousPhotonSource NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testBlockSyntaxDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testBlockSyntaxDensityFunction.exe")
  set_tests_properties(testBlockSyntaxDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testBlockSyntaxDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testBlockSyntaxDensityFunction.exe")
  set_tests_properties(testBlockSyntaxDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testBlockSyntaxDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testBlockSyntaxDensityFunction.exe")
  set_tests_properties(testBlockSyntaxDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testBlockSyntaxDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testBlockSyntaxDensityFunction.exe")
  set_tests_properties(testBlockSyntaxDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testBlockSyntaxDensityFunction NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testChargeTransferRates "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testChargeTransferRates.exe")
  set_tests_properties(testChargeTransferRates PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testChargeTransferRates "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testChargeTransferRates.exe")
  set_tests_properties(testChargeTransferRates PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testChargeTransferRates "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testChargeTransferRates.exe")
  set_tests_properties(testChargeTransferRates PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testChargeTransferRates "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testChargeTransferRates.exe")
  set_tests_properties(testChargeTransferRates PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testChargeTransferRates NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testTemperatureCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testTemperatureCalculator.exe")
  set_tests_properties(testTemperatureCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testTemperatureCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testTemperatureCalculator.exe")
  set_tests_properties(testTemperatureCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testTemperatureCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testTemperatureCalculator.exe")
  set_tests_properties(testTemperatureCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testTemperatureCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testTemperatureCalculator.exe")
  set_tests_properties(testTemperatureCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testTemperatureCalculator NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testEmissivityCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testEmissivityCalculator.exe")
  set_tests_properties(testEmissivityCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testEmissivityCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testEmissivityCalculator.exe")
  set_tests_properties(testEmissivityCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testEmissivityCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testEmissivityCalculator.exe")
  set_tests_properties(testEmissivityCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testEmissivityCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testEmissivityCalculator.exe")
  set_tests_properties(testEmissivityCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testEmissivityCalculator NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testUtilities "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testUtilities.exe")
  set_tests_properties(testUtilities PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testUtilities "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testUtilities.exe")
  set_tests_properties(testUtilities PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testUtilities "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testUtilities.exe")
  set_tests_properties(testUtilities PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testUtilities "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testUtilities.exe")
  set_tests_properties(testUtilities PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testUtilities NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testWorker "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testWorker.exe")
  set_tests_properties(testWorker PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testWorker "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testWorker.exe")
  set_tests_properties(testWorker PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testWorker "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testWorker.exe")
  set_tests_properties(testWorker PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testWorker "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testWorker.exe")
  set_tests_properties(testWorker PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testWorker NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testMassAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testMassAMRRefinementScheme.exe")
  set_tests_properties(testMassAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testMassAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testMassAMRRefinementScheme.exe")
  set_tests_properties(testMassAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testMassAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testMassAMRRefinementScheme.exe")
  set_tests_properties(testMassAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testMassAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testMassAMRRefinementScheme.exe")
  set_tests_properties(testMassAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testMassAMRRefinementScheme NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testSPHNGSnapshotDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testSPHNGSnapshotDensityFunction.exe")
  set_tests_properties(testSPHNGSnapshotDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testSPHNGSnapshotDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testSPHNGSnapshotDensityFunction.exe")
  set_tests_properties(testSPHNGSnapshotDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testSPHNGSnapshotDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testSPHNGSnapshotDensityFunction.exe")
  set_tests_properties(testSPHNGSnapshotDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testSPHNGSnapshotDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testSPHNGSnapshotDensityFunction.exe")
  set_tests_properties(testSPHNGSnapshotDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testSPHNGSnapshotDensityFunction NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testDistantStarContinuousPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testDistantStarContinuousPhotonSource.exe")
  set_tests_properties(testDistantStarContinuousPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testDistantStarContinuousPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testDistantStarContinuousPhotonSource.exe")
  set_tests_properties(testDistantStarContinuousPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testDistantStarContinuousPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testDistantStarContinuousPhotonSource.exe")
  set_tests_properties(testDistantStarContinuousPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testDistantStarContinuousPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testDistantStarContinuousPhotonSource.exe")
  set_tests_properties(testDistantStarContinuousPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testDistantStarContinuousPhotonSource NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testAtomic "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testAtomic.exe")
  set_tests_properties(testAtomic PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testAtomic "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testAtomic.exe")
  set_tests_properties(testAtomic PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testAtomic "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testAtomic.exe")
  set_tests_properties(testAtomic PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testAtomic "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testAtomic.exe")
  set_tests_properties(testAtomic PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testAtomic NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testRiemannSolver "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testRiemannSolver.exe")
  set_tests_properties(testRiemannSolver PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testRiemannSolver "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testRiemannSolver.exe")
  set_tests_properties(testRiemannSolver PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testRiemannSolver "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testRiemannSolver.exe")
  set_tests_properties(testRiemannSolver PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testRiemannSolver "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testRiemannSolver.exe")
  set_tests_properties(testRiemannSolver PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testRiemannSolver NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testHydroIntegrator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testHydroIntegrator.exe")
  set_tests_properties(testHydroIntegrator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testHydroIntegrator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testHydroIntegrator.exe")
  set_tests_properties(testHydroIntegrator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testHydroIntegrator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testHydroIntegrator.exe")
  set_tests_properties(testHydroIntegrator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testHydroIntegrator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testHydroIntegrator.exe")
  set_tests_properties(testHydroIntegrator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testHydroIntegrator NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testPhotonPool "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testPhotonPool.exe")
  set_tests_properties(testPhotonPool PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testPhotonPool "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testPhotonPool.exe")
  set_tests_properties(testPhotonPool PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testPhotonPool "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testPhotonPool.exe")
  set_tests_properties(testPhotonPool PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testPhotonPool "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testPhotonPool.exe")
  set_tests_properties(testPhotonPool PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testPhotonPool NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testAsciiFileDensityGridWriter "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testAsciiFileDensityGridWriter.exe")
  set_tests_properties(testAsciiFileDensityGridWriter PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testAsciiFileDensityGridWriter "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testAsciiFileDensityGridWriter.exe")
  set_tests_properties(testAsciiFileDensityGridWriter PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testAsciiFileDensityGridWriter "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testAsciiFileDensityGridWriter.exe")
  set_tests_properties(testAsciiFileDensityGridWriter PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testAsciiFileDensityGridWriter "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testAsciiFileDensityGridWriter.exe")
  set_tests_properties(testAsciiFileDensityGridWriter PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testAsciiFileDensityGridWriter NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testOldVoronoiGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testOldVoronoiGrid.exe")
  set_tests_properties(testOldVoronoiGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testOldVoronoiGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testOldVoronoiGrid.exe")
  set_tests_properties(testOldVoronoiGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testOldVoronoiGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testOldVoronoiGrid.exe")
  set_tests_properties(testOldVoronoiGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testOldVoronoiGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testOldVoronoiGrid.exe")
  set_tests_properties(testOldVoronoiGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testOldVoronoiGrid NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testPointLocations "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testPointLocations.exe")
  set_tests_properties(testPointLocations PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testPointLocations "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testPointLocations.exe")
  set_tests_properties(testPointLocations PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testPointLocations "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testPointLocations.exe")
  set_tests_properties(testPointLocations PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testPointLocations "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testPointLocations.exe")
  set_tests_properties(testPointLocations PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testPointLocations NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testBinarySearchTree "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testBinarySearchTree.exe")
  set_tests_properties(testBinarySearchTree PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testBinarySearchTree "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testBinarySearchTree.exe")
  set_tests_properties(testBinarySearchTree PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testBinarySearchTree "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testBinarySearchTree.exe")
  set_tests_properties(testBinarySearchTree PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testBinarySearchTree "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testBinarySearchTree.exe")
  set_tests_properties(testBinarySearchTree PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testBinarySearchTree NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testWMBasicPhotonSourceSpectrum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testWMBasicPhotonSourceSpectrum.exe")
  set_tests_properties(testWMBasicPhotonSourceSpectrum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testWMBasicPhotonSourceSpectrum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testWMBasicPhotonSourceSpectrum.exe")
  set_tests_properties(testWMBasicPhotonSourceSpectrum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testWMBasicPhotonSourceSpectrum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testWMBasicPhotonSourceSpectrum.exe")
  set_tests_properties(testWMBasicPhotonSourceSpectrum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testWMBasicPhotonSourceSpectrum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testWMBasicPhotonSourceSpectrum.exe")
  set_tests_properties(testWMBasicPhotonSourceSpectrum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testWMBasicPhotonSourceSpectrum NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testInterpolatedDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testInterpolatedDensityFunction.exe")
  set_tests_properties(testInterpolatedDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testInterpolatedDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testInterpolatedDensityFunction.exe")
  set_tests_properties(testInterpolatedDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testInterpolatedDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testInterpolatedDensityFunction.exe")
  set_tests_properties(testInterpolatedDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testInterpolatedDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testInterpolatedDensityFunction.exe")
  set_tests_properties(testInterpolatedDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testInterpolatedDensityFunction NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testFractalDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testFractalDensityFunction.exe")
  set_tests_properties(testFractalDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testFractalDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testFractalDensityFunction.exe")
  set_tests_properties(testFractalDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testFractalDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testFractalDensityFunction.exe")
  set_tests_properties(testFractalDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testFractalDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testFractalDensityFunction.exe")
  set_tests_properties(testFractalDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testFractalDensityFunction NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testVoronoiDensityGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testVoronoiDensityGrid.exe")
  set_tests_properties(testVoronoiDensityGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testVoronoiDensityGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testVoronoiDensityGrid.exe")
  set_tests_properties(testVoronoiDensityGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testVoronoiDensityGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testVoronoiDensityGrid.exe")
  set_tests_properties(testVoronoiDensityGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testVoronoiDensityGrid "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testVoronoiDensityGrid.exe")
  set_tests_properties(testVoronoiDensityGrid PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testVoronoiDensityGrid NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testOIAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testOIAMRRefinementScheme.exe")
  set_tests_properties(testOIAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testOIAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testOIAMRRefinementScheme.exe")
  set_tests_properties(testOIAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testOIAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testOIAMRRefinementScheme.exe")
  set_tests_properties(testOIAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testOIAMRRefinementScheme "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testOIAMRRefinementScheme.exe")
  set_tests_properties(testOIAMRRefinementScheme PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testOIAMRRefinementScheme NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testHilbertKeyGenerator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testHilbertKeyGenerator.exe")
  set_tests_properties(testHilbertKeyGenerator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testHilbertKeyGenerator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testHilbertKeyGenerator.exe")
  set_tests_properties(testHilbertKeyGenerator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testHilbertKeyGenerator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testHilbertKeyGenerator.exe")
  set_tests_properties(testHilbertKeyGenerator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testHilbertKeyGenerator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testHilbertKeyGenerator.exe")
  set_tests_properties(testHilbertKeyGenerator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testHilbertKeyGenerator NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testSpiralGalaxyDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testSpiralGalaxyDensityFunction.exe")
  set_tests_properties(testSpiralGalaxyDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testSpiralGalaxyDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testSpiralGalaxyDensityFunction.exe")
  set_tests_properties(testSpiralGalaxyDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testSpiralGalaxyDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testSpiralGalaxyDensityFunction.exe")
  set_tests_properties(testSpiralGalaxyDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testSpiralGalaxyDensityFunction "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testSpiralGalaxyDensityFunction.exe")
  set_tests_properties(testSpiralGalaxyDensityFunction PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testSpiralGalaxyDensityFunction NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testSpiralGalaxyContinuousPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testSpiralGalaxyContinuousPhotonSource.exe")
  set_tests_properties(testSpiralGalaxyContinuousPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testSpiralGalaxyContinuousPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testSpiralGalaxyContinuousPhotonSource.exe")
  set_tests_properties(testSpiralGalaxyContinuousPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testSpiralGalaxyContinuousPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testSpiralGalaxyContinuousPhotonSource.exe")
  set_tests_properties(testSpiralGalaxyContinuousPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testSpiralGalaxyContinuousPhotonSource "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testSpiralGalaxyContinuousPhotonSource.exe")
  set_tests_properties(testSpiralGalaxyContinuousPhotonSource PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testSpiralGalaxyContinuousPhotonSource NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testCCDImage "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testCCDImage.exe")
  set_tests_properties(testCCDImage PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testCCDImage "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testCCDImage.exe")
  set_tests_properties(testCCDImage PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testCCDImage "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testCCDImage.exe")
  set_tests_properties(testCCDImage PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testCCDImage "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testCCDImage.exe")
  set_tests_properties(testCCDImage PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testCCDImage NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testDustSimulation "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testDustSimulation.exe")
  set_tests_properties(testDustSimulation PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testDustSimulation "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testDustSimulation.exe")
  set_tests_properties(testDustSimulation PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testDustSimulation "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testDustSimulation.exe")
  set_tests_properties(testDustSimulation PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testDustSimulation "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testDustSimulation.exe")
  set_tests_properties(testDustSimulation PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testDustSimulation NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testDustSimulation1 "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testDustSimulation1.exe")
  set_tests_properties(testDustSimulation1 PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testDustSimulation1 "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testDustSimulation1.exe")
  set_tests_properties(testDustSimulation1 PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testDustSimulation1 "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testDustSimulation1.exe")
  set_tests_properties(testDustSimulation1 PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testDustSimulation1 "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testDustSimulation1.exe")
  set_tests_properties(testDustSimulation1 PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testDustSimulation1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testIonizationSimulation "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testIonizationSimulation.exe")
  set_tests_properties(testIonizationSimulation PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testIonizationSimulation "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testIonizationSimulation.exe")
  set_tests_properties(testIonizationSimulation PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testIonizationSimulation "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testIonizationSimulation.exe")
  set_tests_properties(testIonizationSimulation PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testIonizationSimulation "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testIonizationSimulation.exe")
  set_tests_properties(testIonizationSimulation PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testIonizationSimulation NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testCMILibrary "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testCMILibrary.exe")
  set_tests_properties(testCMILibrary PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testCMILibrary "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testCMILibrary.exe")
  set_tests_properties(testCMILibrary PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testCMILibrary "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testCMILibrary.exe")
  set_tests_properties(testCMILibrary PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testCMILibrary "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testCMILibrary.exe")
  set_tests_properties(testCMILibrary PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testCMILibrary NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testCMIFortranLibrary "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testCMIFortranLibrary.exe")
  set_tests_properties(testCMIFortranLibrary PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testCMIFortranLibrary "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testCMIFortranLibrary.exe")
  set_tests_properties(testCMIFortranLibrary PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testCMIFortranLibrary "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testCMIFortranLibrary.exe")
  set_tests_properties(testCMIFortranLibrary PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testCMIFortranLibrary "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testCMIFortranLibrary.exe")
  set_tests_properties(testCMIFortranLibrary PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testCMIFortranLibrary NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testCMICLibrary "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testCMICLibrary.exe")
  set_tests_properties(testCMICLibrary PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testCMICLibrary "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testCMICLibrary.exe")
  set_tests_properties(testCMICLibrary PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testCMICLibrary "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testCMICLibrary.exe")
  set_tests_properties(testCMICLibrary PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testCMICLibrary "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testCMICLibrary.exe")
  set_tests_properties(testCMICLibrary PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testCMICLibrary NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testDiffuseReemissionHandler "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testDiffuseReemissionHandler.exe")
  set_tests_properties(testDiffuseReemissionHandler PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testDiffuseReemissionHandler "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testDiffuseReemissionHandler.exe")
  set_tests_properties(testDiffuseReemissionHandler PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testDiffuseReemissionHandler "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testDiffuseReemissionHandler.exe")
  set_tests_properties(testDiffuseReemissionHandler PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testDiffuseReemissionHandler "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testDiffuseReemissionHandler.exe")
  set_tests_properties(testDiffuseReemissionHandler PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testDiffuseReemissionHandler NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testTimeLine "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testTimeLine.exe")
  set_tests_properties(testTimeLine PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testTimeLine "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testTimeLine.exe")
  set_tests_properties(testTimeLine PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testTimeLine "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testTimeLine.exe")
  set_tests_properties(testTimeLine PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testTimeLine "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testTimeLine.exe")
  set_tests_properties(testTimeLine PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testTimeLine NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testGradientCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testGradientCalculator.exe")
  set_tests_properties(testGradientCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testGradientCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testGradientCalculator.exe")
  set_tests_properties(testGradientCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testGradientCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testGradientCalculator.exe")
  set_tests_properties(testGradientCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testGradientCalculator "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testGradientCalculator.exe")
  set_tests_properties(testGradientCalculator PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testGradientCalculator NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testMaskedPhotonSourceSpectrum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testMaskedPhotonSourceSpectrum.exe")
  set_tests_properties(testMaskedPhotonSourceSpectrum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testMaskedPhotonSourceSpectrum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testMaskedPhotonSourceSpectrum.exe")
  set_tests_properties(testMaskedPhotonSourceSpectrum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testMaskedPhotonSourceSpectrum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testMaskedPhotonSourceSpectrum.exe")
  set_tests_properties(testMaskedPhotonSourceSpectrum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testMaskedPhotonSourceSpectrum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testMaskedPhotonSourceSpectrum.exe")
  set_tests_properties(testMaskedPhotonSourceSpectrum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testMaskedPhotonSourceSpectrum NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testSPHArrayInterface "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testSPHArrayInterface.exe")
  set_tests_properties(testSPHArrayInterface PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testSPHArrayInterface "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testSPHArrayInterface.exe")
  set_tests_properties(testSPHArrayInterface PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testSPHArrayInterface "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testSPHArrayInterface.exe")
  set_tests_properties(testSPHArrayInterface PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testSPHArrayInterface "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testSPHArrayInterface.exe")
  set_tests_properties(testSPHArrayInterface PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testSPHArrayInterface NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testLambertW "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testLambertW.exe")
  set_tests_properties(testLambertW PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testLambertW "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testLambertW.exe")
  set_tests_properties(testLambertW PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testLambertW "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testLambertW.exe")
  set_tests_properties(testLambertW PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testLambertW "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testLambertW.exe")
  set_tests_properties(testLambertW PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testLambertW NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testBondiProfile "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testBondiProfile.exe")
  set_tests_properties(testBondiProfile PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testBondiProfile "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testBondiProfile.exe")
  set_tests_properties(testBondiProfile PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testBondiProfile "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testBondiProfile.exe")
  set_tests_properties(testBondiProfile PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testBondiProfile "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testBondiProfile.exe")
  set_tests_properties(testBondiProfile PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testBondiProfile NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testHydroMask "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testHydroMask.exe")
  set_tests_properties(testHydroMask PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testHydroMask "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testHydroMask.exe")
  set_tests_properties(testHydroMask PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testHydroMask "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testHydroMask.exe")
  set_tests_properties(testHydroMask PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testHydroMask "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testHydroMask.exe")
  set_tests_properties(testHydroMask PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testHydroMask NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testPointMassExternalPotential "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testPointMassExternalPotential.exe")
  set_tests_properties(testPointMassExternalPotential PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testPointMassExternalPotential "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testPointMassExternalPotential.exe")
  set_tests_properties(testPointMassExternalPotential PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testPointMassExternalPotential "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testPointMassExternalPotential.exe")
  set_tests_properties(testPointMassExternalPotential PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testPointMassExternalPotential "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testPointMassExternalPotential.exe")
  set_tests_properties(testPointMassExternalPotential PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testPointMassExternalPotential NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testMD5Sum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Debug/testMD5Sum.exe")
  set_tests_properties(testMD5Sum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testMD5Sum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/Release/testMD5Sum.exe")
  set_tests_properties(testMD5Sum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testMD5Sum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/MinSizeRel/testMD5Sum.exe")
  set_tests_properties(testMD5Sum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testMD5Sum "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test/RelWithDebInfo/testMD5Sum.exe")
  set_tests_properties(testMD5Sum PROPERTIES  WORKING_DIRECTORY "C:/Users/YW/Documents/GitHub/CMacIonize/0/rundir/test")
else()
  add_test(testMD5Sum NOT_AVAILABLE)
endif()
